# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b407ff81455d30db1c08ff38c5482b7645d1d0dd7fec6d23dc653bf77521f0de167e65c941d0bf9da3f21ad60c1d79c781f9ca38625d25652f991366b834fbde

test:
  secret_key_base: a65caee2e103e74228e68f80540a08549d346fef6103c19f07a4dfbcb47548553a6eb25d1eca704a2f44df72bb7a822a60df9edc29196b80d67264f5c15830ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
